version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      PREDICTION_API_URL: http://model_inference_endpoint:8000/get-prediction/


  model_inference_endpoint:
    build:
      context: .
      dockerfile: ./model-inference-endpoint/Dockerfile
    volumes:
      - ../data:/usr/src/app/data
    environment:
      MODEL_URI: /usr/src/app/data/models
    ports:
      - "8000:8000"
